import { Assistant } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import GlobalProvider from '@/components/application/GlobalProvider';

const assistantFont = Assistant({
  weight: ['400','500','600','700','800'],
  subsets: ['latin'],
  display: 'swap'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body
        className={`${assistantFont.className } antialiased`}
      >
        <GlobalProvider>
        <ToastContainer />
        {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
